Draft: initial formal verification results
IBM/ACE-RISCV pull request #69
Opened 2024-07-12 14:00 UTC by lgaeher

## Description of the changes
This MR adds our initial verification results.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x ] Formal verification
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactorization (non-breaking change which improves code quality)

## How to test this PR?
Follow the instructions in `verification/setup.md` to set the formal verification up.
Alternatively, the `verify` pipeline in CI tests the verification results.

2024-07-12 14:02 UTC, lgaeher commented
I still want to make a pass over the annotations and add a bit more documentation before merging it.
But the `verification/README.md` is ready for review.

2024-07-15 12:15 UTC, wojciechozga requested changes
I left a few comments proposing minor changes. I think you are trying to bring the old version of page_allocator which can be simply deleted.

2024-07-15 12:15 UTC, wojciechozga commented on security-monitor/src/core/page_allocator/allocator.rs
> +        self.max_allocable_page_size = Some(smaller_size);
well spotted!
I think it was still working fine because the max_allocable_page_size was then recalculated again based on children's largest available page_size. But, with your fix we satisfy the spec.

2024-07-15 12:15 UTC, wojciechozga commented on security-monitor/src/core/page_allocator/allocator.rs
> +        ensure!(self.max_allocable_page_size >= Some(page_size_to_acquire), Error::OutOfPages())?;
well spotted! 

looks like it was actually a bug and when we would try to allocate a page that is not available, this code would panic. Something to keep for the paper to say that using formal methods helps to spot these kinds of bugs

2024-07-15 12:15 UTC, wojciechozga commented on security-monitor/src/core/page_allocator/page.rs
> +        // TODO: ideally, use strict-provenance API
Do you mean?
```
#![feature(strict_provenance)]
#![warn(fuzzy_provenance_casts)]
```

We should indeed use it

2024-07-15 12:15 UTC, wojciechozga commented on security-monitor/src/core/page_allocator/page_allocator.rs
this file is outdated or? We use the new version of page allocator these days which is in "core/page_allocator/allocator.rs"

2024-07-16 13:14 UTC, lgaeher commented on security-monitor/src/core/page_allocator/page.rs
> +        // TODO: ideally, use strict-provenance API
Yeah, exactly. We should ideally use `pointer::addr()` to convert pointers to integers (instead of `as usize`), and `pointer::with_addr()` to convert integers to pointers within a known allocation. This will make reasoning quite a bit easier. 

This is not something we need to fix now, but I could make a follow-up MR that adapts the code for that.

2024-07-16 13:21 UTC, lgaeher commented on verification/readme.md
> +
Yep, that sounds good. I'll add a config option for that to RefinedRust.

2024-07-16 13:25 UTC, lgaeher commented on security-monitor/Makefile
> +	echo "Generating OpenSBI bindings" ;\
Ah, yeah, that makes sense

2024-07-16 13:27 UTC, lgaeher commented on Makefile
> +	rm -rf $(ACE_DIR)/security_monitor/verify/
I guess it makes things a bit easier, but probably does not make much of a difference.
Would you prefer to put it in `security-monitor/verification`? If so, I can change it.
Alternatively, we can also decide to change the location in the future.

2024-07-16 13:28 UTC, lgaeher commented on security-monitor/src/core/page_allocator/page_allocator.rs
Good catch, I included it by accident and will remove it.

2024-07-17 09:33 UTC, wojciechozga commented on security-monitor/src/core/page_allocator/page.rs
> +        // TODO: ideally, use strict-provenance API
Sounds good to me. We can add it with another MR.

2024-07-17 09:39 UTC, wojciechozga approved these changes
Thank you for all the changes. It looks good to me!

2024-07-18 16:17 UTC, wojciechozga approved these changes
LGTM

2024-07-18 18:49 UTC, lgaeher commented
Thanks for reviewing! As far as I’m concerned, this should be ready for merging, but maybe @shinnar and @gdhh can take a look at the README first.

2024-07-18 19:24 UTC, shinnar approved these changes
I am not thrilled with current path names: `verification/generated_code/ace/proofs/`, because it is under `generated_code` does not look like a manually curated / checked in object.  However, I don't have any better suggestions at the moment :-).  Anyway, the README.md clearly explains things, and I do not think bikeshedding the path name should hold up this PR.

2024-07-19 07:15 UTC, lgaeher commented
Thanks for reviewing! I agree that the path name is not ideal. We could change it to `rust_proofs`, I think that might capture the content better. What do you think?

2024-07-19 11:29 UTC, gdhh commented on security-monitor/src/core/memory_layout/mod.rs
> +/// Invariant: the non-confidential memory region comes before the confidential memory region.
I do not have a problem with this requirement but it does not appear necessary. What is necessary is that the memory in the confidential region is not in the non-confidential region and the memory in the non-confidential region is not in the confidential region. Specifying this property would be more complex although it can easily be expressed mathematically. Requiring one to appear before the other meets this requirement and is a simpler expression. However we will have to address this eventually, if/when we get to dynamic page allocation. At that point the location (address range) cannot be used as a synonym for state. We have to show that each page is either confidential or non-confidential.

2024-07-19 11:46 UTC, shinnar commented
> Thanks for reviewing! I agree that the path name is not ideal. We could change it to `rust_proofs`, I think that might capture the content better. What do you think?

I agree that would be a better name.  Also, do we need the ace/ subfolder?

2024-07-19 12:16 UTC, gdhh commented on security-monitor/src/core/page_allocator/page.rs
> +    /// Specification:
As we were discussing the other day. It is fine to write to an unallocated page, in part because we want to clear the contents of an unallocated page before moving it to allocated state to eliminate side channels. Also, when the memory is first initialized it is all unallocated, so we need to clear it to remove random values from power on. This only needs to be done once, after that we need to consistently zero memory either when going from allocated to unallocated, or unallocated to allocated, or both. Nevertheless,  it seems that we should require that a page be in allocated state for a read to work. I have not gotten through everything yet. If we clear pages before moving to unallocated state

2024-07-19 12:17 UTC, lgaeher commented on security-monitor/src/core/memory_layout/mod.rs
> +/// Invariant: the non-confidential memory region comes before the confidential memory region.
Indeed, it is not necessary, we would just have to require that the two regions are disjoint. (But this property is satisfied by our current implementation)
I'm not sure what you mean by dynamic page allocation.

I'd suggest we leave this requirement as-is for now, and then generalize it later when it becomes necessary. If you want, I could add a TODO note that we might want to generalize it.

2024-07-19 12:32 UTC, wojciechozga commented on security-monitor/src/core/memory_layout/mod.rs
> +/// Invariant: the non-confidential memory region comes before the confidential memory region.
"dynamic page allocation" is a mechanism defined in RISC-V CoVE spec to move pages between non-confidential and confidential memory. We do not implement it because we are using "static memory partitioning", also defined in the CoVE spec. We argue that "static memory partitioning" is simpler to prove and thus is the preferred way for the deployment model 3 in the CoVE spec. Moving to the "dynamic page allocation" is a significant breaking change, so I doubt we do it, especially since we target more embedded systems rather than cloud.

To implement "dynamic page allocation" one could use (1) MMU for configuring confidential/non-confidential (by running the security monitor in HS-mode and hypervisor in VS-mode and controlling conf/non-conf via MMU) or (2) dedicated hardware like Smmtt. Our approach runs security monitor in M-mode, uses PMP to split between confidential and non-confidential, and MMU for confidential VM isolation.

2024-07-19 12:34 UTC, gdhh commented on verification/readme.md
> +We annotate the Rust source code of the security monitor with verification annotations.
Perhaps: Our approach to proving code in the security monitor is to insert the verification annotations into the code.

insert could be place, write, add ....

2024-07-19 12:34 UTC, wojciechozga commented on security-monitor/src/core/memory_layout/mod.rs
> +/// Invariant: the non-confidential memory region comes before the confidential memory region.
I agree that this requirement should not block the current PR and we can generalize it later.

2024-07-19 12:34 UTC, gdhh commented on verification/readme.md
> +
In general the person needs to change.

2024-07-19 12:35 UTC, gdhh commented on verification/readme.md
> +Afterwards, we use RefinedRust to translate the Rust source code and annotations into a representation in the Coq proof assistant.
Afterwards, RefinedRust translates .....

2024-07-19 12:36 UTC, gdhh commented on verification/readme.md
> +It is split into two subfolders, [`generated`](/verification/generated_code/ace/generated) and [`proofs`](/verification/generated_code/ace/proofs).
There are two subfolders,

2024-07-19 12:47 UTC, gdhh commented on verification/readme.md
> +These files may be modified, as they are not touched by RefinedRust after their initial creation, and may contain partially manual proofs.
These files can be modified because they are not touched by RefinedRust after their initial creation. If the proof is not complete (correct) manual proof steps will need to be added to complete the proof of the function.

The phrase about manual proofs is correct, but manual proofs would not be generated by refined rust.

I am not sure about what you mean by "after their initial creation".  For example, if someone goes in a modified the Rust code eventually should that cause everything to be regenerated? All of our annotations are manual right now, so if the rust code is modified does someone has to add/inspect/the annotations?  This may be one of the areas where we would like to add some automation ...

2024-07-19 12:53 UTC, gdhh commented on verification/readme.md
> +
Question: do you mean some less interesting verified support modules are not in the table or do you mean we are not verifying "less interesting" support modules? Hopefully the former. If so, somewhere we need to list the less interesting modules that have been verified (does not have to be in the readme).

2024-07-19 12:57 UTC, gdhh commented on verification/readme.md
> +These opt-out annotations help to progressively cover code with specification and delay the work on the verification itself. Eventually, a fully verified security monitor would not use any of the opt
..... would not use .... ==> ... would not have ....

2024-07-19 13:00 UTC, gdhh commented on verification/readme.md
> +On the journey to getting a fully verified virtualization stack, this project just considers a part of the necessary components (albeit an important one).
We can be a bit more direct:
A fully verified virtualization stack required a number of components, this project is focused on only one of those necessary components.

2024-07-19 13:01 UTC, gdhh commented on verification/readme.md
> +There are several efforts which are complementary to the aims of this project:
There are several efforts focused on other required components

2024-07-19 13:13 UTC, gdhh commented on Makefile
> +	rm -rf $(ACE_DIR)/security_monitor/verify/
I tagree with putting the verification  in  security-monitor/verification because this location reinforces the point that the verification is part of the project.

2024-07-19 13:30 UTC, shinnar commented on verification/readme.md
> +It is split into two subfolders, [`generated`](/verification/generated_code/ace/generated) and [`proofs`](/verification/generated_code/ace/proofs).
if this was intended as a reply to my comment above:
yes, generated and proofs.  I was referring to ace.  concretely, I am proposing 
`rust_proofs/generated` and `rust_proofs/proofs` (or maybe even `rust_proofs/src`?)

2024-07-19 16:05 UTC, lgaeher commented
> I agree that would be a better name. Also, do we need the ace/ subfolder?

I guess the `ace` subfolder could be renamed, maybe to `security_monitor`.  It is there because there are other crates with utility functions, like the pointer utility crate, which we should also verify. Then we would have more subfolders, one for each crate.

2024-07-19 16:10 UTC, shinnar commented
yes, I think that renaming to `security_monitor` makes sense.  So the path schema would be
- `rust_proofs/CRATE_NAME/generated`
- `rust_proofs/CRATE_NAME/proofs`

2024-07-19 16:24 UTC, lgaeher commented on verification/readme.md
> +
The former, these are not in the table. 

I think if someone wants to be able to tell precisely how far we are, they can check this by looking at the annotated Rust files. Anything very detailed is likely prone to getting outdated easily or imposing a high maintenance burden. Probably the high-level modules are something that people will be interested in, but not which auxiliary functions precisely are verified.

But maybe we can discuss this more offline, if it's not required for this MR?

2024-07-19 16:28 UTC, lgaeher commented on verification/readme.md
> +These files may be modified, as they are not touched by RefinedRust after their initial creation, and may contain partially manual proofs.
I'll change the text to your suggestion, that's a good point.

If someone modifies the Rust code and this breaks the proofs, then someone will have to fix the proofs. This may be because the annotations are now wrong/ the specification is wrong.
The intended workflow is that you change the code, and if everything continues to work, you don't have to inspect anything. Only if something breaks, you know that some work is needed to get the proofs working again.
(Of course, if you change the Rust code by adding new functions, you will generally have to write specifications for those.)

2024-07-19 16:35 UTC, lgaeher commented on verification/readme.md
> +It is split into two subfolders, [`generated`](/verification/generated_code/ace/generated) and [`proofs`](/verification/generated_code/ace/proofs).
I think `proofs` is a bit clearer than `src`

2024-07-19 16:37 UTC, lgaeher commented
> yes, I think that renaming to `security_monitor` makes sense. So the path schema would be

Actually, it's currently called `ace` not because of a RefinedRust-specific naming scheme, but because the Rust crate is called `ace` in `security-monitor/Cargo.toml`. Renaming it would also affect how clients can link to it, but not sure if it is used that way by anyone currently. @wojciechozga do you think it's a good idea to rename the crate, or would you prefer to keep it at `ace`?

2024-07-19 16:39 UTC, lgaeher commented on verification/readme.md
> +
What do you mean? Would you like one of `The user annotates...` or `The Rust sourcecode is annotated...` (passive voice) better? Or do you have something else in mind?

2024-07-19 16:50 UTC, lgaeher commented on security-monitor/src/core/page_allocator/page.rs
> +    /// Specification:
> But for the proof, do we need to say that the state of the page is allocated because this would cause the proof to fail if in the future someone defined read for unallocated pages.

For the proof it does not matter whether the page is `Allocated` or `Unallocated` -- in either case, it is safe to perform a read. Only defining it for `Allocated` pages is a safeguard against logic errors (which would also be caught once we verify it), but does not change the verification.

I can make the change to only allowing reads for `Allocated` pages also in this MR, but any changes to the implementation that change the point where we need to zeroize should probably happen in a separate MR.

2024-07-19 20:43 UTC, wojciechozga commented on security-monitor/src/core/page_allocator/page.rs
> +    /// Specification:
Thanks. I agree, we can address the page zeroing in a separate MR.

2024-07-19 20:47 UTC, wojciechozga commented on verification/readme.md
> +
I agree that we cannot keep the README to detailed because we will most likely get out of sync with the source code. So a high level concepts should be enough at this stage. Once the verification is complete we might think to be more specific because the frequency of changes will be much smaller. All in all, I would keep it like it is now. We can discuss during our Monday sync meetings.

2024-07-19 20:53 UTC, wojciechozga approved these changes
I made a pass over the changes after all comments and it looks ready to be merged.

2024-07-19 21:00 UTC, merged